name: Build Vue
on: 
  push:
    branches: [ main ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./toolcomparer
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '16.x'
    - name: Install npm
      run: npm install
    - name: Install Vue CLI
      run: npm install -g @vue/cli
    - name: Build
      run: npm run build
    - name: Add dist N commit
      run: git add dist && git commit -m "Initial dist subtree commit"
    - name: Push to gh pages
      run: git subtree push --prefix dist origin gh-pages
