name: Build Vue
on: 
  push:
    branches: [ main ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./toolcomparer
    steps:
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v2
    
    - name: CD Load CLI Build
      uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm install -g vue
    - run: npm install -g @vue/cli
    - run: npm run build
      
    
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
