name: Build Vue
on: 
  push:
    branches: [ main ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./toolcomparer
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm install -g @vue/cli
    - run: npm run build
    - name: Publish generated content to GitHub Pages
    - run: git add dist && git commit -m "Initial dist subtree commit"
    - run: git subtree push --prefix dist origin gh-pages
