name: Build Vue
on: 
  push:
    branches: [ main ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./toolcomparer
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Install npm
      run: npm install
    - name: Build
      run: npm run build
    - name: CD
      run: cd dist
    - name: Config Git
      run: git config --global user.name "ZDI-StephanJoneleit"
    - name: Init Git
      run: git init
    - name: Add Git
      run: git add -A
    - name: Commit Git
      run: git commit -m 'deploy'
    - name: Push Git
      run: git push -f ***github.com/zeiss-digital-innovation/ToolComparision.git main:gh-pages
