name: Build Vue
on: 
  push:
    branches: [ main ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./toolcomparer
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'zeiss-digital-innovation'
        reponame: 'ToolComparision'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
