name: Build Vue
on: 
  push:
    branches: [ main ]
    
permissions:
  contents: read
  pull-requests: write

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./toolcomparer
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install npm
      run: npm install
    - name: Build
      run: npm run build
    - name: CD
      run: cd dist
    - name: Init Git
      run: git init
    - name: Verify Git
      run: git config --global user.name "ZDI-StephanJoneleit"
    - name: Add Git
      run: git add -A
    - name: Commit Git
      run: git commit -m 'deploy'
    - name: Push Git
      run: git push -f github.com/zeiss-digital-innovation/ToolComparision.git master:gh-pages
