name: Build Vue
on: 
  push:
    branches: [ main ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v2
    
    - name: Load CLI
      uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm install -g vue
    - run: npm install -g @vue/cli
    - run: npm run build
      
    
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
